name: Metrics
on:
  # schedule:
  # - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: luisdinicco
          template: classic
          theme: tokyonight
          base: header, activity, community, repositories
          config_display: large
          config_border: none

          # ğŸ“Š GitHub Stats
          plugin_lines: yes

          # ğŸŒ Top Languages
          plugin_languages: yes
          plugin_languages_layout: compact
          plugin_languages_sections: most-used
          plugin_languages_limit: 8

          # ğŸ† Trophies
          plugin_trophies: yes
          plugin_trophies_limit: 8
